### ISSUE TITLE
Пофиксить upstream-sync.yaml

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#10]
## Описание

У нас есть [скриптец](https://github.com/ThetaStation/ThetaStation/actions/workflows/upstream-sync.yml) который каждую пятницу в 10 утра по UTC должен синхронизировать нашу ветку `main` с веткой `master` от https://github.com/space-wizards/space-station-14

Но если глянуть на его логи, можно увидеть что:
1. Он не синхронизирует субмодуль движка (RobustToolbox), из-за чего конфликты которые не разрешаются возникают там
2. Он не имеет прав пушить в нашу ветку в связи с каким-то приколом с аутентификацией (fatal: could not read Username for 'https://github.com/': No such device or address)

По поводу проблемы 1:
- Вероятно можно поменять команду мержа так, чтобы игнорились субмодули. Для этого надо будет форкнуть этот гитхаб экшон (Fork-Sync-With-Upstream) и написать свою (А так же сделать ишуй в репо того экшена о том чтобы добавили такой конфиг (параметры мержа))
- В случае если первое невозможно, надо экшену добавить шаг запуска `python RUN_THIS.py` который обновит версию движка и все-все-все библиотеки сам по себе.

По поводу проблемы 2 у меня вообще мыслей нет.

**Воспроизведение**

Запустить [скриптец](https://github.com/ThetaStation/ThetaStation/actions/workflows/upstream-sync.yml), убедиться что ничего не произошло.

**Comment by KIBORG04** [comment]
так там не только с субмодулем связано, пишет же что конфликты есть, а значит `Automatic merge failed; fix conflicts and then commit the result.`

**Comment by KIBORG04** [comment]
https://github.com/ThetaStation/ThetaStation/pull/19
