### ISSUE TITLE
Лагучие коллизии при респавне командой

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#102]
### Описание

Когда респавнитесь то респавнитесь все друг в дружке и происходят коллизии и в итоге долго разбегаться.

### Шаги воспроизведения

1. Умереть командой из двух и более человек
2. Зареспавниться
3. Страдать

**Comment by LudwigVonChesterfield** [comment]
Это пофикшено?

**Comment by ilinm1** [comment]
никто ничего не менял, но вообще я ни разу не страдал от коллизий на спавне. мб при спавне корабля трясло сильно и вам показалось что это всё от коллизий...
