### ISSUE TITLE
Изменить ghost.role_time в конфигах на 0

### ISSUE THREAD

**Issue by KIBORG04** [ThetaStation/ThetaStation#11]
Изменить ghost.role_time на 0

**Comment by Dushess0** [comment]
https://docs.spacestation14.io/en/getting-started/debugging-tools

![image](https://user-images.githubusercontent.com/44201461/204057706-dc3b6b6f-31ff-4ec0-a64d-cb81b34b3999.png)

sudo cvar ghost.role_time 0
restartroundnow

лучше так будет поменять. И так можно любые переменные менять, что бы не ждать пока я обновлю конфиг

**Comment by KIBORG04** [comment]
Я у себя такое писал и оно сбросилось после рестарта

**Comment by KIBORG04** [comment]
поставил на 1, так как при 0 из окошка спавна пропадает весь текст-описание
