### ISSUE TITLE
Выключать ООК на время раунда.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#12]
## Описание

ООК во время раунда отвлекает игроков на внестанционные дела, чем уменьшает вовлеченность в то что происходит с их драгоценными куклами. Его следует выключить.

**Цели**

Увеличить вовлеченность игроков в игру.

**Методы**

Минимизировать отвлекающие от игры элементы, такие как "вне-игровой чат".

**Комментарий**

Что делать с ЛООК-ом?

**Comment by UDaV73rus** [comment]
Это стоит делать когда уже появится какой-никакой онлайн

**Comment by KIBORG04** [comment]
Уже закодили лол
https://github.com/space-wizards/space-station-14/pull/8981

**Comment by EmoGarbage404** [comment]
Just as a note, it is a cvar that can be enabled and disabled, just in case you want it off while your server is still growing.
