### ISSUE TITLE
Госты Дюпаются

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#134]
### Описание

Каждый раз когда умирает команда, гостов спавнится в два раза больше чем нужно. Возможно просто старые госты не удаляются.

### Шаги воспроизведения

1. Умереть всей командой (к примеру подорвав консоль)
2. Повторить шаг 1
3. Убедиться что гостов слишком много

**Comment by ilinm1** [comment]
неактуально
