### ISSUE TITLE
Корабли Спавнятся Внутри Обломков, Других Кораблей

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#136]
### Описание

При респавне корабля он может заспавниться поверх существующих на карте обломков, или даже другого корабля!

При чем он не вылетает из структуры мгновенно, а жутко лагает и неприятно для всех на корабле трясётся.

(P.S.: то что клещи иногда рандомно спавнились на корабле было прикольно...)

### Шаги воспроизведения

1. Заспавнить корабль.
2. Повторять пункт 1 пока не заспавнитесь внутри астероида.

**Comment by ilinm1** [comment]
Неактуально (#125 + в #128 другая система но я тоже потестил чтоб коллизий не было)
