### ISSUE TITLE
UI Селектор Цвета Команды

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#138]
### Описание

Очень важная QoL фича отсутствие которой мгновенно опускает билд до уровня "поделка на коленях".

Приоритет конечно не самый высокий, но если такое где-то есть в билде то стоит заюзать.

**Comment by ilinm1** [comment]
уже давно неактуально

**Comment by LudwigVonChesterfield** [comment]
С каких пор у нас есть юайка выбора цвета команды вместо "впишите сюда хекс код"

**Comment by ilinm1** [comment]
#150 , я даже там референснул этот ишуй
