### ISSUE TITLE
Худ Таймер Респавна

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#141]
### Описание

Без него ожидание респавна чувствуется несправедливым и часто задаешься вопросом "А РАЗВЕ Я НЕ ДОЛЖЕН УЖЕ ЗАРЕСПАВНИТЬСЯ"?

Как и #138 важная QoL фича отсутствие которой делает грустно.

**Comment by KIBORG04** [comment]
https://github.com/ThetaStation/ThetaStation/pull/470
