### ISSUE TITLE
"Матчмейкинг"

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#144]
### Описание

Сейчас можно создавать сколько угодно команд, и создавать несбалансированные команды где слишком много людей против слишком мало.

Предлагаю добавить две следующие системы:
- Лимит команд скейлящийся от кол-ва игроков. Условно на каждых 5 игроков +1 к лимиту команд
- Лимит игроков в команде по принципу "мин кол-во среди всех команд + 1". То есть если во всех командах уже есть 2 игрока, то лимит 3, но если хоть в одной ещё 1 человек, лимит 2.

**Comment by ilinm1** [comment]
и это закройте
