### ISSUE TITLE
В дробовике 50 патронов вместо 100

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#154]
### Описание

В названии всё сказано.

Если так и задумано - то полосочка должна была быть полностью заполненной.

### Шаги воспроизведения

1. Зарядить дробовик
2. Открыть консоль пиу-пиу

### Скриншоты

![image](https://user-images.githubusercontent.com/17705613/235372938-f06062f9-35ad-4d68-ba62-8daee1ff461a.png)

**Comment by ilinm1** [comment]
а чего ты сам это не пофиксишь, однострочная штука ведь
