### ISSUE TITLE
Нужен фидбек о том что команда создаётся

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#155]
### Описание

Сейчас если команда создаётся во время подгрузки карты нет никакого фидбека о том что "да, мы создаём команду, подождите..." и в итоге тыкаешь несколько раз ждёшь злишься что ничего не происходит и выглядит как баг...

### Шаги воспроизведения

1. Зайти в начале раунда
2. Тыкнуть по консоли команд
3. "Создать команду"
4. Обнаружить что ничего нигде не происходит.

**Comment by ilinm1** [comment]
хз насколько актуально, ибо щас фидбека не может быть из-за спавна астероидов заранее, предполагается что геймрул добавляется до старта раунда/воутом на режим/при спавне первой консоли
