### ISSUE TITLE
Неизвестные Мелкие Объекты (НМО)

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#156]
### Описание

При генерации астероидов маленькие астероиды которые раньше даже не показывались бы на радаре из-за размера имеют метку "Неизвестно", засоряя карту.

### Шаги воспроизведения

1. Сгенерировать карту
2. Обнаружить НМО

### Скриншоты

![image](https://user-images.githubusercontent.com/17705613/235373027-b2070cbb-646f-49b8-8ca9-96534654d5dc.png)

**Comment by ilinm1** [comment]
#122 разве не пофиксил? он от 14 апреля, этот ишуй от 30
