### ISSUE TITLE
Проверка препятствий турелей сбоит

### ISSUE THREAD

**Issue by ilinm1** [ThetaStation/ThetaStation#173]
### Описание

https://github.com/ThetaStation/ThetaStation/assets/57045293/74e82a98-cce9-43aa-8b7f-fd6b2adde4d6

^ пример когда стреляют когда не надо

https://github.com/ThetaStation/ThetaStation/assets/57045293/28812f60-1bfe-41a6-8255-90b3a48a4b33

^ пример когда не стреляют когда надо

### Шаги воспроизведения

помаппить 5 секунд

**Comment by LudwigVonChesterfield** [comment]
предлагаю чтобы снаряды не могли попасть в свой же корабль первых секунд 2 полёта

**Comment by ilinm1** [comment]
поправка: второй пример некорректен, там другое сломано

**Comment by LudwigVonChesterfield** [comment]
ещё два варианта решений:

у турелей переменные минимального и максимального угла поворота

каким-то образом подтягивать возможные углы стрельбы при прикручивании консоли стрельбы

**Comment by LudwigVonChesterfield** [comment]
ещё в дискорде предлагал рейкастить не туда куда игрок кликнул, а на клик + мин разброс и клик + макс разброс пускать рейкасты.

**Comment by ilinm1** [comment]
ну типо неактуально
