### ISSUE TITLE
Broken Ammo Count Indicators

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#186]
### Описание

The ammo counter line doesn't scale with the amount of ammo left over in the ammo container.

### Шаги воспроизведения

1. Spawn any ship
2. Load ammo
3. Shoot some shots
4. Witness the bug

### Скриншоты

![image](https://github.com/ThetaStation/ThetaStation/assets/17705613/b4b5c65f-ee8c-4fb6-bd31-52bcdcbae889)

**Comment by ilinm1** [comment]
счётчики вроде снова сломались, хз почему

**Comment by ilinm1** [comment]
окей, это неправда
