### ISSUE TITLE
Respawn Spot Issue

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#187]
### Описание

@KIBORG04 thinks that teams respawn in the same spot each time.

I'd also like to add that respawns consistently occur outside of the playing field for some reason.

### Шаги воспроизведения

1. Die
2. Respawn

**Comment by ilinm1** [comment]
unsure if this is still true, seems like the issue was because of broken play area borders

**Comment by ilinm1** [comment]
okay, this is 100% outdated
