### ISSUE TITLE
Split Grids Have Names

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#190]
### Описание

Split up grids, that shattered off a ship shouldn't have names, otherwise they bunch up and make the game map unreadable due to the mess of text on it.

### Скриншоты

![image](https://github.com/ThetaStation/ThetaStation/assets/17705613/b02afd8b-dfb1-465a-ae49-356141060f06)

**Comment by ilinm1** [comment]
resolved by #194
