### ISSUE TITLE
[Proposal] Don't shrink playing field

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#192]
### Описание

It worked in Fortnite because players don't respawn and thus that is not a problem to consider.

Shrinking fields lessen the amount of places a ship can respawn thus causing more spawn camping.

**Comment by ilinm1** [comment]
this can be already disabled just by tweaking gamemode prototype btw

**Comment by ilinm1** [comment]
resolved by #197
