### ISSUE TITLE
[Proposal] Respawn Invulnerability To Prevent Spawn Camping

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#193]
### Описание

Currently spawn camping is a big issue:
- Ships come with ammo unloaded and thus can't shoot back
- Even if they could they are out of position without much choice

I believe that ships should be protected for some time after respawning from any damage, but don't have the ability to shoot otherwise it could be abused.

**Comment by LudwigVonChesterfield** [comment]
I have to admit when playing with only 2 teams this doesn't seem much like a issue at the moment.

**Comment by LudwigVonChesterfield** [comment]
Another point recently discovered, is that when the ship just spawns it isn't fully initialized immediately, and players get spawn camped in that period, especially on the Arrow.

**Comment by ilinm1** [comment]
#428
