### ISSUE TITLE
New lobby arts

### ISSUE THREAD

**Issue by ilinm1** [ThetaStation/ThetaStation#204]
### Описание

Half of them are poorly drawn, the rest does not match current gamemode's theme. If we can't find anything worthy it's still better to put random spacecraft/space pictures instead imo.

**Comment by LudwigVonChesterfield** [comment]
I think we should do an arts context as soon as we get popular.

**Comment by LudwigVonChesterfield** [comment]
We've boiled down to the good ones. Can this be closed @IlinMihail ?
