### ISSUE TITLE
Сканеры и разведка

### ISSUE THREAD

**Issue by Mercurialaste** [ThetaStation/ThetaStation#221]
### Описание

Уменьшить радиус видимости шаттлов у консолей турелей до 300-400 метров, у консоли пилота до 500 метров. *(Числа примерные и зависят от масштаба карты.)*

Радиус видимости людей уменьшить до обшивки и внутренности самого шаттла, с которого производится просмотр радара. *(Чтобы абордажников было видно или если они уже на шаттле, или если они на его обшивке.)*

Добавить радарам разделение на свой/чужой, чтобы с помощью них было явно видно, кто на шаттле является врагом, а кто союзником.

*(Может когда-нибудь добавят что-то вроде стелс костюмов воксов или стелс модулей на риги, которые также помогут скрывать присутствие абордажной команды.)*

В качестве разведки дальнего действия, добавить что-то вроде просвета на сектор, это может быть как разделенная на карте сетка по 250 метров, в которой сканер затрагивает 3-4 клеток сетки в радиусе, т.е. создавая своеобразную окружность. *(Если нет возможности конечно, сделать фиксированные круги радиусом 750-1000 метров.)*

**Comment by LudwigVonChesterfield** [comment]
Переношу в публичный репо.
