### ISSUE TITLE
Аркадный ремонт шаттлов

### ISSUE THREAD

**Issue by Mercurialaste** [ThetaStation/ThetaStation#222]
### Описание

Пишу, основываясь на том, что 1 раунд идет 30 минут, по этому все временные промежутки примерны.

Каждые 6 минут после начала боя. *(В самом начале возможность перезаряжается.)* Давать возможность за N-ное количество очков команды, полностью ремонтировать и пополнять боекомплект шаттла, без возможности его смены, ремонт занимает от 30 секунд до 1 минуты, на усмотрение того, кто закодит, я пока слабо представляю себе, насколько динамичны у нас бои, но расчет на то, что команде победившей в бою, вместо самоличного уничтожения шаттла можно будет его отремонтировать без больших затрат по времени, как раз к моменту, когда отреспавнится убитая ими команда.

Вкупе с ишуем насчет сканеров, люди смогут на время ремонта быть в относительной безопасности на время ремонта.

Это может быть как тупо переспавн шаттла на том же месте, где находится текущий. *(В этом случае, хорошо было бы, если бы это все было достаточно плавно и незаметно.)* 

В качестве ограничений, в случае нанесения урона или активного движения/стрельбы с самого шаттла, отменять ремонт шаттла или восполняя очки или забирая их.

Использовать эту возможность можно дать или капитану команды, если тот жив или каждому члену команды, будет это отдельное устройство или OOC способность -- решайте уже сами, но оба варианта имеют свои плюсы. *(Консоль ремонта в таком случае, получает стратегическую ценность, а OOC возможность, позволяет в любом случае отремонтировать корабль.)*

**Comment by LudwigVonChesterfield** [comment]
#53

**Comment by LudwigVonChesterfield** [comment]
https://github.com/ThetaStation/ThetaStation-Public/issues/2
