### ISSUE TITLE
[Proposal][QoL] Random Available Team Color Button

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#254]
### Описание

Pressing this button would pick a random viable team color.

Perhaps it should just pick a random color, as currently our color limitation does not scale to amount of teams, and perhaps a server with 10 or 20 teams could run out of colors to pick and be locked out of the game because of that.

Perhaps just removing the color sliders and only allowing to pick a random color would also be good as it would make it easier to jump into the fight without randomly adjusting color sliders.

**Comment by KIBORG04** [comment]
feature is removed
