### ISSUE TITLE
[Proposal] *Ship Loading* screen

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#270]
### Description

When there's a team playing a big ship and it respawns everyone gets a wave of lags

Assuming that this lag wave can not be fixed, I propose to at least let people know that it's not a server that's struggling from all the action but rather something really laggy occuring

If ship's partcount or some other measure of laginess exceeds some threshold (for example, Box ship shouldn't cause this screen) everyone on the server should get a "Ship Respawning, please wait. Blame RobustToolbox" screen.

Thus players can blame the RobustToolbox engine rather than us!

**Comment by LudwigVonChesterfield** [comment]
I don't know, was this a problem when we got the more powerful server?

@KIBORG04

**Comment by KIBORG04** [comment]
Not a problem
