### ISSUE TITLE
Erroneous "Abandoned" Team Deletion

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#314]
### Description

- If there's only 1 player in a team and their game crashes (they "leave"), the team is deleted (even though it obviously shouldn't?)
- If a team is deleted the player is ghosted and can't return to the game to make a new team. I think they should be either spawned in lobby, or also have the go to lobby button

### Reproduction steps

1. Create a team
2. Leave the game
3. See both of the side effects described above

**Comment by ilinm1** [comment]
интендед бехавиор
