### ISSUE TITLE
У моих кодо-ПРов нет никакой индекации Theta

### ISSUE THREAD

**Issue by KIBORG04** [ThetaStation/ThetaStation#33]
### Описание

Конкретно нужно создать папки или комментарии в:
https://github.com/ThetaStation/ThetaStation/pull/27
https://github.com/ThetaStation/ThetaStation/pull/20
https://github.com/ThetaStation/ThetaStation/pull/21

**Comment by LudwigVonChesterfield** [comment]
Да и пофиг уже наверное?
