### ISSUE TITLE
Automatic Anti-Self Grief System Doesn't Work With Shotguns

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#351]
### Description

When shooting a shotgun you can shoot your own ship with the spread-out projectiles.

Perhaps the arc calculation method does not take into account multiple projectiles of a gun?

### Reproduction steps

1. Pick Boxship (why is it not just called "The Box"?)
2. Angle the shotgun shot at ~89 degrees
3. See one of the projectiles hit your own ship
4. Cry.

**Comment by LudwigVonChesterfield** [comment]
Maybe instead of prohibiting such shots we should disallow collisions with own ship in first ~10 seconds of flight?

Maybe we should block the projectiles that would hit own ship but not prohibit the entire shot?

**Comment by ilinm1** [comment]
#428
