### ISSUE TITLE
Мул и скипджек снова не загружаются

### ISSUE THREAD

**Issue by ilinm1** [ThetaStation/ThetaStation#356]
### Description

не загружаются через loadgrid, но нормально спавнятся в обычном шипивенте

### Reproduction steps

mapping 2
loadgrid 2 /Maps/Theta/Shipevent/Ships/shipevent-mule.yml
краш/спам рантаймами на релизе

**Comment by KIBORG04** [comment]
а зачем loadgrid, если есть mapping или loadmap. Я их через savemap сохраняю
