### ISSUE TITLE
Правки бебраланса и qol

### ISSUE THREAD

**Issue by KIBORG04** [ThetaStation/ThetaStation#41]
### Описание

1. Положение ракет на радаре должно обновляться постоянно без большого кд. Можно, конечно, сделать и предикшен, но я думаю это пиздец.
2. Для уничтожения шаттла надо хранить ссылку на грид, а не метку. Удалять и членов тимы.
3. Добавить еще шкафов с пушками на моих два корабля

**Comment by ilinm1** [comment]
4. сделать для отображения тим нормальный интерфейс вместо сообщения в чат от сервера, ибо мне лень

**Comment by KIBORG04** [comment]
5. Писать название шаттла в гост кнопках

**Comment by KIBORG04** [comment]
(сделано все кроме 5)
