### ISSUE TITLE
Уменьшить чувствительность наклонения шаттлов

### ISSUE THREAD

**Issue by Mercurialaste** [ThetaStation/ThetaStation#42]
### Описание

При управлении шаттлом и повороте на q/e слишком сильное наклонение за нажатие, дополненное инерцией, которая доворачивает шаттл ещё немного в бок. 

Да и в принципе, шаттлы бы немного замедлить, но сделать более плавными в управлении.

*(Хз, зависит ли это от конструкции текущих шаттлов.)*

**Comment by KIBORG04** [comment]
Решено удалением старых шаттлов
