### ISSUE TITLE
Шип Тест: Капитанский Режим

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#52]
### Описание

Координировать команды тяжело из-за того что нет функционала вне игры и надо как-то договариваться по дискордам там и т.д., предлагаю добавить "Капитанский" режим ивенту:

* Спавнить не спавнер команды, а спавнер капитана.
* Капитан выбирает имя корабля, размер команды, и может добавить вайтлист по сикеям
* После того как капитан всё это сделал появляется спавнер самой команды

**Comment by KIBORG04** [comment]
Для формирования команд лучше новое окно придумать, которое будет работать как лобби. Но наверное об этом стоит задуматься на поздних этапах, когда (если) вдруг захотим стать публичным хайповым билдом

**Comment by LudwigVonChesterfield** [comment]
По сути это закодили?

**Comment by ilinm1** [comment]
ну кеп фактически ничем не отличается от обычного экипажа пока, а так да
