### ISSUE TITLE
Хочу Механ Починки

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#53]
### Описание

Если сделать какую-то казуальненькую починку вида трать металл восстанавливай тайл шаттла до его первобытной формы то было бы круто забавно роль инженера на борту больше решений чиниться и убегать/стреляться до последнего, чинить движки/чинить пушки и т.д. ...

Если будет такая починка то можно дать ещё инструмент быстрого разбора чтобы лутать врагов на ресурс для починки.

**Comment by ilinm1** [comment]
туфта по моему делать такой казуальный механ

**Comment by LudwigVonChesterfield** [comment]
https://github.com/ThetaStation/ThetaStation-Public/issues/2
