### ISSUE TITLE
Клонилка Вместо Год Мода

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#58]
### Описание

Если на корабли добавить клонировочный аппарат который мгновенно создаёт клона умершего члена экипажа, можно не выдавать годмод куклам.

Я бы предложил сделать эту машинку переносимой чтобы её можно было брать с собой на абордаж, или перепрятывать)

**Comment by KIBORG04** [comment]
Надо автореспавн спустя секунд 20

**Comment by ilinm1** [comment]
респавн самих членов тимы мгновенный, зато корабли респавнятся по таймеру (#63 ). мб стоит закрыть

**Comment by LudwigVonChesterfield** [comment]
Я бы предпочёл чтобы и клонилка тоже была, и её соответственно можно было сломать... И соответственно починить.

так ведь чуточку интересней

**Comment by ilinm1** [comment]
её можно сломать, и это геймовер для тимы (аналогично консоли). починку вместо респавна легко сделать, но мне кажется если вы допустили врага к своей клонилке, то заслужили деспавна

**Comment by ilinm1** [comment]
закройте, всё как в ишью теперь
