### ISSUE TITLE
Удаление Корабля из-за Смерти Команды удаляет Абордажников

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#65]
### Описание

Если умирает вся команда во время абордажа, удаляются люди которые абордировали кораблик.

Возможно стоит в таком случае их телепортировать к своему клонподу, или когда добавят #58 хотя бы респавнить.

Полное удаление корабля кстати частично конфликтует с #53

**Comment by LudwigVonChesterfield** [comment]
Может лучше удалять только консольку пилотирования чтобы метки пропадали с радара, но кораблик оставался чтобы его лутать (или использовать как укрытие)

**Comment by ilinm1** [comment]
Я всё равно в новом ПРе респавню корабль тимы через минуту, а сдохшие обордажники могут сразу респавнится, так что это вряд-ли проблема

**Comment by LudwigVonChesterfield** [comment]
> а сдохшие обордажники могут сразу респавнится, так что это вряд-ли проблема

У команд лимит игроков, пока нет респавна человека в команде немного сомнительный контраргумент

**Comment by ilinm1** [comment]
ролька остаётся и у госта, поэтому он всегда сможет зареспавнится. ну либо за него это делать

**Comment by LudwigVonChesterfield** [comment]
> Возможно стоит в таком случае их телепортировать к своему клонподу, или когда добавят https://github.com/ThetaStation/ThetaStation/issues/58 хотя бы респавнить.

Было бы круто если бы они телепортировались к клонподу а не удалялись-респавнились, потому-что получается что теряешь аммуницию и лут, но по сути ишуй можно закрыть.
