### ISSUE TITLE
Консоль управление надо припрятать

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#66]
### Описание

Смерть консоли = смерть корабля, соответственно её надо спрятать куда-то в центр чтобы не было внезапных смертей.

(Возможно стоит убрать удаление корабля при смерти консоли, перенимая опыт того же Робокрафта)

**Comment by ilinm1** [comment]
тоже непонятно насколько актуально, щас все передние консоли защищены достаточно + пилоты должны защищать голову от попаданий, так что это скилл ишуй если вам взорвали мостик
