### ISSUE TITLE
Визуализация Вектора Перемещения

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#67]
### Описание

Консолям турелей и пилотирования добавить вектор направления как в Баротравме показывающий куда летит шаттл (и длиной вектора скорость)

**Comment by ilinm1** [comment]
а имеет ли это вообще смысл? в баротравме так сделали ибо у 90% подлодок огромная инерция. здесь же можно полностью затормозить тяжёлый корабль зажав пробел на 3 секунды

**Comment by LudwigVonChesterfield** [comment]
Это нужно для более просто "коммуникации" между пилотом и стрелками.
