### ISSUE TITLE
Колёсико Эмоутов для координации без войс чата

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#68]
### Описание

Что-то типо как в Доте, выбирать "На правый борт!" "Враг слева!" и т.д.

**Comment by KIBORG04** [comment]
надо еще тим-чат

**Comment by LudwigVonChesterfield** [comment]
Тим чат наверное можно реализовать рандомной частотой в наушнике?

**Comment by LudwigVonChesterfield** [comment]
У нас теперь есть пинги на карте, думаю они покрывают юзкейсы
