### ISSUE TITLE
Магазины для турелей с дробовиком можно заряжать в обычный бульдог

### ISSUE THREAD

**Issue by Mercurialaste** [ThetaStation/ThetaStation#69]
### Описание

Используя запасные магазины для турелей с дробовиком, можно зарядить бульдог, увеличив его боезапас с 8-9 жаканов, до 100-101.

*(Скорее всего, то же самое будет и с магазинами на пилу.)*

**Comment by LudwigVonChesterfield** [comment]
А если стрелять боезапасом турели из бульдога взрывы будут? Если да то очевидно это фича.

**Comment by KIBORG04** [comment]
Все будет как с турелями, но с боезопасом 100

**Comment by Mercurialaste** [comment]
*(В том числе и налипающие на спрайт гильзы.)*

**Comment by LudwigVonChesterfield** [comment]
По сути это пофиксили?

**Comment by ilinm1** [comment]
да
