### ISSUE TITLE
Мини шаттлы

### ISSUE THREAD

**Issue by Mercurialaste** [ThetaStation/ThetaStation#70]
### Добавление консоли для управления и стрельбы.

Предполагается использовать эти консоли на небольших шаттлах с 1-2 пушками спереди.

Сами шаттлы рассчитаны на одного человека без замороченных систем больших шаттлов.
Из того, что должно быть:
* Минимальный Атмос
* СМЕС с энергией
* Шкаф для хранения запасных магазинов

Из того, что не обязательно:
* Двигатель, производящий энергию для СМЕСов
* Генератор гравитации
* МедБлок

*(Если это возможно, было бы неплохо регулировать скорость шаттлов в зависимости от их размера, но как понимаю, сейчас это зависит только от количества двигателей.)*

**Comment by ilinm1** [comment]
фактически два шаттла на одного человека уже имеются, правда там раздельные консоли, но вполне можно два окна за раз открыть
