### ISSUE TITLE
Опознавательные знаки команд

### ISSUE THREAD

**Issue by Mercurialaste** [ThetaStation/ThetaStation#73]
### Описание

Любые, в том числе ООС знаки, вроде худ роли, позволяющие узнать принадлежность к команде, стоящего перед тобой космонавта.

Разный цвет брони, иконка рядом с куклой, обладающая своим цветом и видимая всем и тд.

**Comment by ilinm1** [comment]
#79 и название тимы в имени куклы решают данные проблемы, наверное стоит закрыть
