### ISSUE TITLE
Таран

### ISSUE THREAD

**Issue by Mercurialaste** [ThetaStation/ThetaStation#74]
### Описание

Столкновение шаттла с структурами и тд. наносит урон шаттлу и структуре, в зависимости от их скорости.

**Comment by LudwigVonChesterfield** [comment]
С таранами хорошо сочетались бы какие-нибудь минишаттлы на одного игрока. Возможно даже целый тип кораблей - авианосцы с такими шаттлами).

**Comment by LudwigVonChesterfield** [comment]
#97
