### ISSUE TITLE
ПВО Пилоту

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [ThetaStation/ThetaStation#96]
### Описание

У пилота заняты стрелочки для пилотирования но не занята мышка, предлагаю пилоту дать ПВО.

Какие-то снаряды которые позволяют сбивать другие снаряды...

**Comment by LudwigVonChesterfield** [comment]
Я понимаю что сейчас пилот *может* это делать открыв второе окошко, но какие подводные интегрировать ПвО в его радар управления?

@KIBORG04 @IlinMihail 

Два окошка лично я рассматриваю как усложнение и условную награду за догадливость + ловкость играть с загаженным интерфейсом.

**Comment by KIBORG04** [comment]
Проблем нет, но я бы сначала хотел бы успеть доделать свой гига рефакторик, который позволит такое делать ещё проще

**Comment by ilinm1** [comment]
щас такое уже можно реализовать но тогда на существующих кораблях пустое место появится. можно считать неактуально
